# Generated by Django 3.2.8 on 2021-10-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrylist',
            fields=[
                ('countryName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('continentName', models.CharField(max_length=20)),
                ('nationLeader', models.CharField(max_length=20)),
                ('nLeadertype', models.CharField(choices=[('Prime Minister', 'Prime Minister'), ('President', 'President'), ('Chancellor', 'Chancellor'), ('king', 'king')], max_length=20)),
                ('population', models.IntegerField(max_length=20)),
                ('nationalLanguage', models.CharField(max_length=20)),
                ('capitalName', models.CharField(max_length=20)),
                ('stateCount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
