# Generated by Django 3.2.8 on 2021-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylist',
            name='capitalName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='continentName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='nationLeader',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='nationalLanguage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countrylist',
            name='stateCount',
            field=models.IntegerField(null=True),
        ),
    ]
